# Generated by Django 5.2.10 on 2026-01-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dependencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
