# Generated by Django 5.2.10 on 2026-01-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Código de activo')),
                ('equipment_type', models.CharField(choices=[('desktop', 'PC Escritorio'), ('laptop', 'Laptop')], max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('retired', 'Retirado')], default='active', max_length=15)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='organization.classroom')),
                ('assigned_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='organization.person')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.site')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('ap', 'Access Point'), ('patchpanel', 'Patch Panel'), ('firewall', 'Firewall')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(help_text='Rack, piso, sala, etc.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('down', 'Fuera de servicio')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='organization.classroom')),
                ('assigned_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='organization.person')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.site')),
            ],
        ),
    ]
