# Generated by Django 5.2.10 on 2026-01-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('peripheral_type', models.CharField(choices=[('keyboard', 'Teclado'), ('mouse', 'Ratón'), ('monitor', 'Monitor'), ('printer', 'Impresora'), ('scanner', 'Escáner'), ('webcam', 'Webcam'), ('headset', 'Auriculares'), ('ups', 'UPS'), ('other', 'Otro')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('retired', 'Retirado')], default='active', max_length=15)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripherals', to='organization.classroom')),
                ('assigned_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripherals', to='organization.person')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.site')),
            ],
        ),
    ]
