# Generated by Django 5.2.10 on 2026-01-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_peripheral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de activo'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
