import { Fragment, useState, useEffect } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import api from "../api/axios";
import Spinner from '../components/Spinner';

// NetworkDeviceForm component (nested inside NetworkDeviceModal for simplicity)
const NetworkDeviceForm = ({ device, onSubmit, onCancel, sites, loading }) => {
  const [formData, setFormData] = useState({
    asset_tag: '',
    device_type: 'router',
    brand: '',
    model: '',
    serial_number: '',
    ip_address: '',
    mac_address: '',
    location: '',
    status: 'active',
    site: '',
    notes: '',
  });
  const [formError, setFormError] = useState('');

  useEffect(() => {
    if (device) {
      setFormData({
        asset_tag: device.asset_tag || '',
        device_type: device.device_type || 'router',
        brand: device.brand || '',
        model: device.model || '',
        serial_number: device.serial_number || '',
        ip_address: device.ip_address || '',
        mac_address: device.mac_address || '',
        location: device.location || '',
        status: device.status || 'active',
        site: device.site || '',
        notes: device.notes || '',
      });
    }
  }, [device]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setFormError('');

    // Basic validation
    if (!formData.brand || !formData.model || !formData.serial_number || !formData.site) {
      setFormError('Please fill in all required fields.');
      return;
    }

    // For new devices, asset_tag is generated by the backend, so we don't send an empty one
    const dataToSend = { ...formData };
    if (!device && !dataToSend.asset_tag) {
        delete dataToSend.asset_tag;
    }

    onSubmit(dataToSend);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {formError && <p className="text-red-500 text-sm">{formError}</p>}
      
      <div>
        <label htmlFor="asset_tag" className="block text-sm font-medium text-gray-700">Código de Activo</label>
        <input type="text" name="asset_tag" id="asset_tag" value={formData.asset_tag} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" readOnly={!!device} />
      </div>

      <div>
        <label htmlFor="device_type" className="block text-sm font-medium text-gray-700">Tipo de Dispositivo</label>
        <select name="device_type" id="device_type" value={formData.device_type} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
          <option value="router">Router</option>
          <option value="switch">Switch</option>
          <option value="ap">Access Point</option>
          <option value="patchpanel">Patch Panel</option>
          <option value="firewall">Firewall</option>
        </select>
      </div>

      <div>
        <label htmlFor="brand" className="block text-sm font-medium text-gray-700">Marca</label>
        <input type="text" name="brand" id="brand" value={formData.brand} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required />
      </div>

      <div>
        <label htmlFor="model" className="block text-sm font-medium text-gray-700">Modelo</label>
        <input type="text" name="model" id="model" value={formData.model} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required />
      </div>

      <div>
        <label htmlFor="serial_number" className="block text-sm font-medium text-gray-700">Número de Serie</label>
        <input type="text" name="serial_number" id="serial_number" value={formData.serial_number} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required />
      </div>

      <div>
        <label htmlFor="ip_address" className="block text-sm font-medium text-gray-700">Dirección IP</label>
        <input type="text" name="ip_address" id="ip_address" value={formData.ip_address} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" />
      </div>

      <div>
        <label htmlFor="mac_address" className="block text-sm font-medium text-gray-700">Dirección MAC</label>
        <input type="text" name="mac_address" id="mac_address" value={formData.mac_address} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" />
      </div>

      <div>
        <label htmlFor="location" className="block text-sm font-medium text-gray-700">Ubicación</label>
        <input type="text" name="location" id="location" value={formData.location} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" />
      </div>

      <div>
        <label htmlFor="status" className="block text-sm font-medium text-gray-700">Estado</label>
        <select name="status" id="status" value={formData.status} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
          <option value="active">Activo</option>
          <option value="maintenance">En mantenimiento</option>
          <option value="down">Fuera de servicio</option>
        </select>
      </div>

      <div>
        <label htmlFor="site" className="block text-sm font-medium text-gray-700">Sede</label>
        <select name="site" id="site" value={formData.site} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required>
          <option value="">Seleccione una sede</option>
          {sites.map(site => (
            <option key={site.id} value={site.id}>{site.name}</option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-gray-700">Notas</label>
        <textarea name="notes" id="notes" value={formData.notes} onChange={handleChange}
                  rows="3" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"></textarea>
      </div>

      <div className="flex justify-end space-x-2">
        <button type="button" onClick={onCancel}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-gray-500">
          Cancelar
        </button>
        <button type="submit" disabled={loading}
                className="px-4 py-2 text-sm font-medium text-gray-800 bg-indigo-600 rounded-md hover:bg-indigo-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500">
          {loading ? <Spinner /> : (device ? 'Guardar Cambios' : 'Crear Dispositivo de Red')}
        </button>
      </div>
    </form>
  );
};


// NetworkDeviceModal component
const NetworkDeviceModal = ({ isOpen, onClose, device, onSave }) => {
  const [sites, setSites] = useState([]);
  const [loadingForm, setLoadingForm] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (isOpen) {
      const fetchData = async () => {
        try {
          const sitesRes = await api.get('/organization/sites/');
          setSites(sitesRes.data);
        } catch (err) {
          console.error("Failed to fetch form data", err);
          setError("Failed to load necessary form data.");
        } finally {
          setLoadingForm(false);
        }
      };
      fetchData();
    }
  }, [isOpen]);

  const handleSubmit = async (formData) => {
    setSubmitting(true);
    setError('');
    try {
      if (device) {
        // Update existing device
        await api.put(`/assets/network-devices/${device.id}/`, formData);
      } else {
        // Create new device
        await api.post('/assets/network-devices/', formData);
      }
      onSave(); // Notify parent component to refresh data
      onClose(); // Close modal
    } catch (err) {
      console.error("Failed to save network device", err.response?.data || err);
      setError(err.response?.data ? JSON.stringify(err.response.data) : "Failed to save network device.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Transition appear show={isOpen} as={Fragment}>
      <Dialog as="div" className="relative z-10" onClose={onClose}>
        <Transition.Child
          as={Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-black bg-opacity-25" />
        </Transition.Child>

        <div className="fixed inset-0 overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4 text-center">
            <Transition.Child
              as={Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0 scale-95"
              enterTo="opacity-100 scale-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100 scale-100"
              leaveTo="opacity-0 scale-95"
            >
              <Dialog.Panel className="w-full max-w-full sm:max-w-md transform overflow-hidden rounded-2xl bg-white p-4 sm:p-6 text-left align-middle shadow-xl transition-all">
                <Dialog.Title
                  as="h3"
                  className="text-lg font-medium leading-6 text-gray-900"
                >
                  {device ? 'Editar Dispositivo de Red' : 'Crear Nuevo Dispositivo de Red'}
                </Dialog.Title>
                <div className="mt-4">
                  {loadingForm ? (
                    <Spinner />
                  ) : error ? (
                    <p className="text-red-500">{error}</p>
                  ) : (
                    <NetworkDeviceForm
                      device={device}
                      onSubmit={handleSubmit}
                      onCancel={onClose}
                      sites={sites}
                      loading={submitting}
                    />
                  )}
                </div>
              </Dialog.Panel>
            </Transition.Child>
          </div>
        </div>
      </Dialog>
    </Transition>
  );
};

export default NetworkDeviceModal;
