import { Fragment, useState, useEffect } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import api from '../api/axios'; // Corrected import path
import Spinner from '../components/Spinner';

// PeripheralForm component
const PeripheralForm = ({ peripheral, onSubmit, onCancel, sites, persons, classrooms, loading }) => {
  const [formData, setFormData] = useState({
    asset_tag: '',
    peripheral_type: 'keyboard',
    brand: '',
    model: '',
    serial_number: '',
    assigned_to_person: '',
    assigned_to_classroom: '',
    site: '',
    status: 'active',
    purchase_date: '',
    notes: '',
  });
  const [formError, setFormError] = useState('');

  useEffect(() => {
    if (peripheral) {
      setFormData({
        asset_tag: peripheral.asset_tag || '',
        peripheral_type: peripheral.peripheral_type || 'keyboard',
        brand: peripheral.brand || '',
        model: peripheral.model || '',
        serial_number: peripheral.serial_number || '',
        assigned_to_person: peripheral.assigned_to_person || '',
        assigned_to_classroom: peripheral.assigned_to_classroom || '',
        site: peripheral.site || '',
        status: peripheral.status || 'active',
        purchase_date: peripheral.purchase_date || '',
        notes: peripheral.notes || '',
      });
    }
  }, [peripheral]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setFormError('');

    // Basic validation
    if (!formData.brand || !formData.model || !formData.serial_number || !formData.site) {
      setFormError('Please fill in all required fields.');
      return;
    }

    // For new peripherals, asset_tag is generated by the backend, so we don't send an empty one
    const dataToSend = { ...formData };
    if (!peripheral && !dataToSend.asset_tag) {
        delete dataToSend.asset_tag;
    }

    onSubmit(dataToSend);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {formError && <p className="text-red-500 text-sm">{formError}</p>}
      
      <div>
        <label htmlFor="asset_tag" className="block text-sm font-medium text-gray-700">Código de Activo</label>
        <input type="text" name="asset_tag" id="asset_tag" value={formData.asset_tag} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" readOnly={!!peripheral} />
      </div>

      <div>
        <label htmlFor="peripheral_type" className="block text-sm font-medium text-gray-700">Tipo de Periférico</label>
        <select name="peripheral_type" id="peripheral_type" value={formData.peripheral_type} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
          <option value="keyboard">Teclado</option>
          <option value="mouse">Ratón</option>
          <option value="monitor">Monitor</option>
          <option value="printer">Impresora</option>
          <option value="scanner">Escáner</option>
          <option value="webcam">Webcam</option>
          <option value="headset">Auriculares</option>
          <option value="ups">UPS</option>
          <option value="other">Otro</option>
        </select>
      </div>

      <div>
        <label htmlFor="brand" className="block text-sm font-medium text-gray-700">Marca</label>
        <input type="text" name="brand" id="brand" value={formData.brand} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required />
      </div>

      <div>
        <label htmlFor="model" className="block text-sm font-medium text-gray-700">Modelo</label>
        <input type="text" name="model" id="model" value={formData.model} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required />
      </div>

      <div>
        <label htmlFor="serial_number" className="block text-sm font-medium text-gray-700">Número de Serie</label>
        <input type="text" name="serial_number" id="serial_number" value={formData.serial_number} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required />
      </div>

      <div>
        <label htmlFor="status" className="block text-sm font-medium text-gray-700">Estado</label>
        <select name="status" id="status" value={formData.status} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
          <option value="active">Activo</option>
          <option value="maintenance">En mantenimiento</option>
          <option value="retired">Retirado</option>
        </select>
      </div>

      <div>
        <label htmlFor="site" className="block text-sm font-medium text-gray-700">Sede</label>
        <select name="site" id="site" value={formData.site} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" required>
          <option value="">Seleccione una sede</option>
          {sites.map(site => (
            <option key={site.id} value={site.id}>{site.name}</option>
          ))}
        </select>
      </div>
      
      <div>
        <label htmlFor="assigned_to_person" className="block text-sm font-medium text-gray-700">Asignado a Persona</label>
        <select name="assigned_to_person" id="assigned_to_person" value={formData.assigned_to_person} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
          <option value="">No Asignado</option>
          {persons.map(person => (
            <option key={person.id} value={person.id}>{person.first_name} {person.last_name}</option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="assigned_to_classroom" className="block text-sm font-medium text-gray-700">Asignado a Aula</label>
        <select name="assigned_to_classroom" id="assigned_to_classroom" value={formData.assigned_to_classroom} onChange={handleChange}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
          <option value="">No Asignado</option>
          {classrooms.map(classroom => (
            <option key={classroom.id} value={classroom.id}>{classroom.name} ({classroom.site.name})</option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="purchase_date" className="block text-sm font-medium text-gray-700">Fecha de Compra</label>
        <input type="date" name="purchase_date" id="purchase_date" value={formData.purchase_date} onChange={handleChange}
               className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" />
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-gray-700">Notas</label>
        <textarea name="notes" id="notes" value={formData.notes} onChange={handleChange}
                  rows="3" className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"></textarea>
      </div>

      <div className="flex justify-end space-x-2">
        <button type="button" onClick={onCancel}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-gray-500">
          Cancelar
        </button>
        <button type="submit" disabled={loading}
                className="px-4 py-2 text-sm font-medium text-gray-800 bg-indigo-600 rounded-md hover:bg-indigo-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500">
          {loading ? <Spinner /> : (peripheral ? 'Guardar Cambios' : 'Crear Periférico')}
        </button>
      </div>
    </form>
  );
};


// PeripheralModal component
const PeripheralModal = ({ isOpen, onClose, peripheral, onSave }) => {
  const [sites, setSites] = useState([]);
  const [persons, setPersons] = useState([]);
  const [classrooms, setClassrooms] = useState([]);
  const [loadingForm, setLoadingForm] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (isOpen) {
      const fetchData = async () => {
        try {
          const [sitesRes, personsRes, classroomsRes] = await Promise.all([
            api.get('/organization/sites/'),
            api.get('/organization/persons/'),
            api.get('/organization/classrooms/'),
          ]);
          setSites(sitesRes.data);
          setPersons(personsRes.data);
          setClassrooms(classroomsRes.data);
        } catch (err) {
          console.error("Failed to fetch form data", err);
          setError("Failed to load necessary form data.");
        } finally {
          setLoadingForm(false);
        }
      };
      fetchData();
    }
  }, [isOpen]);

  const handleSubmit = async (formData) => {
    setSubmitting(true);
    setError('');
    try {
      // Clean up empty strings for foreign keys
      const dataToSend = { ...formData };
      if (dataToSend.assigned_to_person === '') dataToSend.assigned_to_person = null;
      if (dataToSend.assigned_to_classroom === '') dataToSend.assigned_to_classroom = null;

      if (peripheral) {
        // Update existing peripheral
        await api.put(`/assets/peripherals/${peripheral.id}/`, dataToSend);
      } else {
        // Create new peripheral
        await api.post('/assets/peripherals/', dataToSend);
      }
      onSave(); // Notify parent component to refresh data
      onClose(); // Close modal
    } catch (err) {
      console.error("Failed to save peripheral", err.response?.data || err);
      setError(err.response?.data ? JSON.stringify(err.response.data) : "Failed to save peripheral.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Transition appear show={isOpen} as={Fragment}>
      <Dialog as="div" className="relative z-10" onClose={onClose}>
        <Transition.Child
          as={Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-black bg-opacity-25" />
        </Transition.Child>

        <div className="fixed inset-0 overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4 text-center">
            <Transition.Child
              as={Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0 scale-95"
              enterTo="opacity-100 scale-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100 scale-100"
              leaveTo="opacity-0 scale-95"
            >
              <Dialog.Panel className="w-full max-w-full sm:max-w-md transform overflow-hidden rounded-2xl bg-white p-4 sm:p-6 text-left align-middle shadow-xl transition-all">
                <Dialog.Title
                  as="h3"
                  className="text-lg font-medium leading-6 text-gray-900"
                >
                  {peripheral ? 'Editar Periférico' : 'Crear Nuevo Periférico'}
                </Dialog.Title>
                <div className="mt-4">
                  {loadingForm ? (
                    <Spinner />
                  ) : error ? (
                    <p className="text-red-500">{error}</p>
                  ) : (
                    <PeripheralForm
                      peripheral={peripheral}
                      onSubmit={handleSubmit}
                      onCancel={onClose}
                      sites={sites}
                      persons={persons}
                      classrooms={classrooms}
                      loading={submitting}
                    />
                  )}
                </div>
              </Dialog.Panel>
            </Transition.Child>
          </div>
        </div>
      </Dialog>
    </Transition>
  );
};

export default PeripheralModal;
